mode: load  #可填 load 或populate 。表示在区块加载时还是创建时尝试生成遗迹
Structures:
  test:
    #原理图的路径
    schema: "plugins\FastAsyncWorldEdit\schematics\test.schem"
    #在什么世界生成
    world:
      - world
    height: surface  #可填：具体的y值(整数）区间[1,20] ， sky , surface ,underground
    biomes:  #可填：ALL 所有群系  ， 原版群系 ， 自定义群系 。需要附带命名空间
      - "minecraft:overworld"
    awayFromSpawn: [0,100000]  #距离出生点的2D距离， 填区间
    distanceBetween: 50 #同种遗迹生成的间距
    amountLimit: -1 #同种遗迹生成的数量限制,填-1无限制
    pedestal_material: GRASS_BLOCK #底座的材质
    bottom_material:
      - GRASS_BLOCK   #表示在什么介质上生成,ALL表示所有
    chance: 100  #填0~100的整数，表示满足上述所有条件后,有多少概率生成
